name: Build Images

on:
  push:
    branches: [main]

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push api
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: eddwills95/bos-mode-api:latest

      - name: Build and push client
        id: docker_build_client
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: eddwills95/bos-mode-client:latest

      - name: Image digests
        run: echo api:${{ steps.docker_build_api.outputs.digest }} client:${{ steps.docker_build_client.outputs.digest }}
